apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: clone-repo
        image: registry.access.redhat.com/ubi9/ubi-minimal:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -d /code/.git ]; then
            microdnf install -y git
            git clone https://github.com/Red-Hat-Hackathon/griot-and-grits-backend.git /code
          fi
        volumeMounts:
        - name: code
          mountPath: /code
      containers:
      - name: backend
        image: registry.access.redhat.com/ubi9/nodejs-20:latest
        workingDir: /code
        command: ["/bin/sh", "-c"]
        args:
        - |
          npm install
          npm run dev
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: code
          mountPath: /code
      volumes:
      - name: code
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  labels:
    app: backend
spec:
  to:
    kind: Service
    name: backend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
