apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel9/postgresql-15
        # --- ARGS REMOVED ---
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "hackathon"
        - name: POSTGRESQL_PASSWORD
          value: "hackathon123"
        - name: POSTGRESQL_DATABASE
          value: "hackathon_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
