apiVersion: batch/v1
kind: Job
metadata:
  name: verify-db
spec:
  ttlSecondsAfterFinished: 300  # Auto-delete after 5 minutes
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: verifier
        image: registry.redhat.io/rhel9/python-311
        command: ["/bin/bash", "-c"]
        env:
        - name: PGHOST
          value: "postgres"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: "hackathon"
        - name: PGPASSWORD
          value: "hackathon123"
        - name: PGDATABASE
          value: "hackathon_db"
        args:
        - |
          echo "Installing psycopg2..."
          pip install psycopg2-binary

          echo "Verifying database connection..."
          python3 <<EOF
          import psycopg2
          import os

          DB_CONFIG = {
              "host": os.getenv("PGHOST", "postgres"),
              "port": os.getenv("PGPORT", "5432"),
              "user": os.getenv("PGUSER", "hackathon"),
              "password": os.getenv("PGPASSWORD", "hackathon123"),
              "database": os.getenv("PGDATABASE", "hackathon_db")
          }

          try:
              conn = psycopg2.connect(**DB_CONFIG)
              cursor = conn.cursor()

              cursor.execute("SELECT version();")
              version = cursor.fetchone()
              print(f"✓ PostgreSQL Version: {version[0]}")

              cursor.execute("SELECT * FROM users;")
              rows = cursor.fetchall()
              print(f"✓ Users table data: {rows}")

              conn.close()
              print("\n✓ Database verification successful!")
          except Exception as e:
              print(f"✗ Error: {e}")
              exit(1)
          EOF
