{{- if and .Values.backend.enabled .Values.backend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  labels:
    {{- include "griot-and-grits.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  host: {{ .Values.backend.route.host }}
  to:
    kind: Service
    name: backend
  port:
    targetPort: http
  tls:
    termination: {{ .Values.backend.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.backend.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
